name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build CI
    
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@dev
        with:
          packages: redis-server
          version: 1.0
